service: serverless-lambda

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-east-1

functions:
  generateRandomNumberhello:
    handler: src/handler.generateRandomNumber
    timeout: 60 # seconds
    memorySize: 128 #MB